---
- name: Ensure unattended-upgrades is installed
  apt:
    pkg: unattended-upgrades
    state: present
    update_cache: true
  become: true

- name: Ensure apt-listchanges is installed
  apt:
    pkg: apt-listchanges
    state: present
    update_cache: true
  become: true

- name: Ensure unattended upgrades are configured
  copy:
    src: 50unattended-upgrades
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: 0644
  become: true

- name: Ensure unattended upgrades are enabled
  copy:
    src: 20auto-upgrades
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: 0644
  become: true

