FROM node:16-alpine

ENV NODE_ENV=development

# `git` is needed in the container to install `1-click-bom-minimal` in `package.json`.
RUN apk --no-cache add git

RUN mkdir /app
WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install

COPY . .
