FROM node:14-alpine

ENV NODE_ENV=production

RUN apk --no-cache add git

RUN mkdir /app
WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn --prune-lockfile

COPY . .

CMD sh -c "yarn build && yarn start"
