#!/usr/bin/env python3

"""
Generates Gerber or SVG files from .kicad_pcb

USAGE:
./plot_kicad_pcb gerber x.kicad_pcb output_directory/
./plot_kicad_pcb svg x.kicad_pcb /tmp/directory/ output.svg
"""

import pcbnew
import time
import os
import sys
import glob
import lxml.etree as ET
import copy

from util import remove_color, empty_svg
from shrink_svg import shrink_svg

plot_format = sys.argv[1]
input_file = sys.argv[2]
plot_directory = os.path.abspath(sys.argv[3])
if plot_format == "svg":
    plot_format = pcbnew.PLOT_FORMAT_SVG
    output_file = sys.argv[4]
elif plot_format == "gerber":
    plot_format = pcbnew.PLOT_FORMAT_GERBER
else:
    print(f"Only 'svg' or 'gerber' supported, got: '{plot_format}'")
    sys.exit(1)

board = pcbnew.LoadBoard(input_file)
plot_control = pcbnew.PLOT_CONTROLLER(board)
plot_options = plot_control.GetPlotOptions()
plot_options.SetOutputDirectory(plot_directory)
plot_options.SetPlotFrameRef(False)
plot_options.SetSketchPadLineWidth(pcbnew.FromMM(0.35))
plot_options.SetAutoScale(False)
plot_options.SetMirror(False)
plot_options.SetUseGerberAttributes(False)
plot_options.SetExcludeEdgeLayer(True)
plot_options.SetScale(1)
plot_options.SetUseAuxOrigin(True)
plot_options.SetNegative(False)
plot_options.SetPlotReference(True)
plot_options.SetPlotValue(True)
plot_options.SetPlotInvisibleText(False)
plot_options.SetDrillMarksType(pcbnew.PCB_PLOT_PARAMS.NO_DRILL_SHAPE)

# remove solder mask from silk to be sure there is no silk on pads
plot_options.SetSubtractMaskFromSilk(True)

copper_layer_count = board.GetCopperLayerCount()
plot_plan = (
    [("F_Cu", pcbnew.F_Cu, "Top layer")]
    + [(f"Inner{n}", n, "Inner") for n in range(1, copper_layer_count - 1)]
    + [
        ("B_Cu", pcbnew.B_Cu, "Bottom layer"),
        ("B_Mask", pcbnew.B_Mask, "Mask Bottom"),
        ("F_Mask", pcbnew.F_Mask, "Mask top"),
        ("B_Paste", pcbnew.B_Paste, "Paste Bottom"),
        ("F_Paste", pcbnew.F_Paste, "Paste Top"),
        ("F_SilkS", pcbnew.F_SilkS, "Silk Top"),
        ("B_SilkS", pcbnew.B_SilkS, "Silk Bottom"),
        ("Edge_Cuts", pcbnew.Edge_Cuts, "Edges"),
    ]
)


for (layer_name, layer_id, layer_description) in plot_plan:
    plot_control.SetLayer(layer_id)
    plot_control.OpenPlotfile(layer_name, plot_format, layer_description)
    plot_control.PlotLayer()
    time.sleep(0.01)
    plot_control.ClosePlot()



if plot_format == pcbnew.PLOT_FORMAT_SVG:

    layers = []
    for (layer_name, _, __) in plot_plan:
        fileglob = os.path.join(plot_directory, f"*-{layer_name}.svg")
        (filepath,) = glob.glob(fileglob)
        tree = ET.parse(filepath)
        layers.append((layer_name, tree))

    new_tree = empty_svg()
    new_root = new_tree.getroot()

    for (layer_name, tree) in layers:
        layer = tree.getroot()
        g = ET.SubElement(
            new_root,
            "g",
            {
                "class": f"layer {layer_name.lower()}",
            },
        )
        for child in layer:
            for e in child.iter():
                remove_color(e)
            g.append(child)

    shrink_svg(new_tree, 1)

    folder = os.path.dirname(output_file)
    os.makedirs(folder, exist_ok=True)
    new_tree.write(output_file)

elif plot_format == pcbnew.PLOT_FORMAT_GERBER:
    drill_writer = pcbnew.EXCELLON_WRITER(board)
    drill_writer.SetMapFileFormat(pcbnew.PLOT_FORMAT_PDF)

    mirror = False
    minimal_header = False
    offset = board.GetDesignSettings().GetAuxOrigin()
    merge_npth = True
    drill_writer.SetOptions(mirror, minimal_header, offset, merge_npth)

    metric_format = True
    drill_writer.SetFormat(metric_format)

    gen_drl = True
    gen_map = False
    drill_writer.CreateDrillandMapFilesSet(plot_directory, gen_drl, gen_map)

    # A text file to report drill statistics
    drill_report_filename = plot_directory + "/drill_report.txt"
    drill_writer.GenDrillReportFile(drill_report_filename)
