---
- name: Ensure 'deploy' user's public key is in authorized_keys
  become: true
  authorized_key:
    user: deploy
    state: present
    key: "{{ lookup('file', 'deploy-production.id_rsa.pub') }}"
