#!/usr/bin/env python3

import sys
import pcbnew

input_path = sys.argv[1]
output_folder = sys.argv[2]

board = pcbnew.LoadBoard(input_path)
plot_control = pcbnew.PLOT_CONTROLLER(board)

plot_options = plot_control.GetPlotOptions()
plot_options.SetPlotFrameRef(False)
plot_options.SetOutputDirectory(output_folder)

plot_control.OpenPlotfile("", pcbnew.PLOT_FORMAT_SVG, "")
plot_control.SetColorMode(True)

copper_layer_count = board.GetCopperLayerCount()

layers = (
    [
        pcbnew.B_Fab,
        pcbnew.B_CrtYd,
        pcbnew.B_SilkS,
        pcbnew.B_Cu,
    ]
    + [n for n in range(1, copper_layer_count - 1)]
    + [
        pcbnew.F_Cu,
        pcbnew.F_SilkS,
        pcbnew.F_CrtYd,
        pcbnew.F_Fab,
        pcbnew.Dwgs_User,
        pcbnew.Cmts_User,
        pcbnew.Edge_Cuts,
    ]
)


for layer in layers:
    plot_control.SetLayer(layer)
    plot_control.PlotLayer()

plot_control.ClosePlot()
